project_id = "cieczaajcgkgdgenfdzi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://www.jumpinai.com"
additional_redirect_urls = ["https://lovable.dev", "http://localhost:3000", "https://4a6994dd-87fd-4337-a29d-8d2d56e25570.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.send-newsletter-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-investor-email]
verify_jwt = false

[functions.request-investment-deck]
verify_jwt = false

[functions.download-investment-deck]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.download-product]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = true

[functions.verify-email]
verify_jwt = false

[functions.admin-dashboard-data]
verify_jwt = true

[functions.send-subscription-welcome]
verify_jwt = false

[functions.jumps-ai-coach]
verify_jwt = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324